name: NishthaGupta
favicon: null
layout_spectrum: 0.9574389322660863
typography_spectrum: 0.09067982411943376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.0382858666125685
  lightness: 0.5943417055532336
  saturation: 0.19972991081885993
  rhythmicContrast: 0.6911173567641526
purpose: []
